### PR TITLE
Delete `old_emf`

### PR DESCRIPTION
**Pull request by RaptaG**
I mean, do you need it?

Also, do you need [`fabric-like`](https://github.com/Traben-0/Entity_Model_Features/tree/master/fabric-like) too?

### CODE REVIEW

**Comment by Traben-0** [comment]
There is some stuff in the old folder from the alpha I still plan to copy from in the beta with a planned feature soon

The fabric like directory is a compatibility layer in architectury while forge fabric and quilt read from common only fabric and quilt read from fabric like, while I do not use the quilt folder yet it's there for of quilt ever breaks for the mod in the future and I need it so fabric like stays too

**Comment by RaptaG** [comment]
Actually I'll keep it open and you can merge it when you implement anything you want from there

**Comment by Traben-0** [comment]
I could remove it but there is no harm and saves future reworking with Architectury if I ever need quilt to have a seperate file

**Comment by Traben-0** [comment]
closed as directory has been removed in 1.20-dev

**Comment by RaptaG** [comment]
> closed as directory has been removed in 1.20-dev

Nice

**Pull request closed without merging**
